// USER ACTIONS TYPES
export const ON_USER_AUTH = 'ON_USER_AUTH';
export const ON_USER_AUTH_SUCCESS = 'ON_USER_AUTH_SUCCESS';
export const ON_USER_AUTH_FAIL = 'ON_USER_AUTH_FAIL';
export const ON_USER_LOGOUT = 'ON_USER_LOGOUT';

// ROOMS ACTIONS TYPES
export const ON_ROOMS_VALUE_CHANGE = 'ON_ROOMS_VALUE_CHANGE';
export const ON_ROOM_READING = 'ON_ROOM_READING';
export const ON_ROOM_READ = 'ON_ROOM_READ';
export const ON_ROOM_READ_FAIL = 'ON_ROOM_READ_FAIL';
export const ON_ROOM_CREATING = 'ON_ROOM_CREATING';
export const ON_ROOM_CREATED = 'ON_ROOM_CREATED';
export const ON_ROOM_CREATE_FAIL = 'ON_ROOM_CREATE_FAIL';
export const ON_ROOM_DELETED = 'ON_ROOM_DELETED';

// MESSAGES ACTIONS TYPES
export const ON_MESSAGES_VALUE_CHANGE = 'ON_MESSAGES_VALUE_CHANGE';
export const ON_MESSAGES_READING = 'ON_MESSAGES_READING';
export const ON_MESSAGES_READ = 'ON_MESSAGES_READ';