export const ON_USER_VALUE_CHANGE = 'ON_USER_VALUE_CHANGE';
export const ON_USER_AUTH = 'ON_USER_AUTH';
export const ON_USER_AUTH_SUCCESS = 'ON_USER_AUTH_SUCCESS';
export const ON_USER_AUTH_FAIL = 'ON_USER_AUTH_FAIL';