# Generated by Django 3.0.6 on 2020-06-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200602_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
